GET http://localhost:3001/auth/test

###

POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "login": "user9",
    "nickName": "user9",
    "password": "sliva"
}

###

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
    "login": "podpivasnik228",
    "password": "sliva"
}

###

POST http://localhost:3001/friend-req/add/5f77151035357c543c030ede
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Zjc1ZDI3ODI3MmY5YzUzMDFmMzk0YWIiLCJuaWNrTmFtZSI6InBvZHBpdmFzbmlrMjI4IiwiaWF0IjoxNjAyNjc4MTUwLCJleHAiOjE2MDUyNzAxNTB9.n47LU9rO1sTh-XLW__kvxxaIKxyuu6l8UUB7xJfHIuc

# {
#     "login": "podpivasnik228",
#     "password": "sliva"
# }

###

POST http://localhost:3001/groups/new-group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InBvZHBpdmFzbmlrMjI4Iiwibmlja05hbWUiOiJwb2RwaXZhc25pazIyOCIsImZpcnN0TmFtZSI6IkFydGVtIiwibGFzdE5hbWUiOiJNaXJvbm92IiwiaWF0IjoxNjAxNTU2MDAzLCJleHAiOjE2MDQxNDgwMDN9.LHTEfBk3A2WdlistOgBZu8WPXsiV-AMSRMUEmVOhvmw

{
    "title": "Some Project",
    "description": "Something about this project Something about this project Something about this project Something about this project Something about this project Something about this project",
    "users": [
        "5f75d278272f9c5301f394ab",
        "5f77151e35357c543c030ee0",
        "5f77151035357c543c030ede",
        "5f77154335357c543c030ee5"
    ],
    "tags": ["#tag1", "tag2"]

    
}

###

POST http://localhost:3001/tasks/new-task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InBvZHBpdmFzbmlrMjI4Iiwibmlja05hbWUiOiJwb2RwaXZhc25pazIyOCIsImZpcnN0TmFtZSI6IkFydGVtIiwibGFzdE5hbWUiOiJNaXJvbm92IiwiaWF0IjoxNjAxNTU2MDAzLCJleHAiOjE2MDQxNDgwMDN9.LHTEfBk3A2WdlistOgBZu8WPXsiV-AMSRMUEmVOhvmw

{
    "title": "buy some sugar!!!",
    "description": "there is no sugar in the office",
    "workers": [{
        "_id": "5f75d278272f9c5301f394ab",
        "startTime": "12:20"
    }, {
        "_id": "5f77154335357c543c030ee5"
    }],
    "groupId": "5f77097de66e674a957a16d1",
    "completed": false
}

###

GET http://localhost:3001/groups/5f77097de66e674a957a16d1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InBvZHBpdmFzbmlrMjI4Iiwibmlja05hbWUiOiJwb2RwaXZhc25pazIyOCIsImZpcnN0TmFtZSI6IkFydGVtIiwibGFzdE5hbWUiOiJNaXJvbm92IiwiaWF0IjoxNjAxNTYwNjUwLCJleHAiOjE2MDQxNTI2NTB9.jp0o2BlWNKn-s9gGyBuos883oxy77zAQSzkH42urP_Y


###

GET http://localhost:3001/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InBvZHBpdmFzbmlrMjI4Iiwibmlja05hbWUiOiJwb2RwaXZhc25pazIyOCIsImZpcnN0TmFtZSI6IkFydGVtIiwibGFzdE5hbWUiOiJNaXJvbm92IiwiaWF0IjoxNjAxNTU2MDAzLCJleHAiOjE2MDQxNDgwMDN9.LHTEfBk3A2WdlistOgBZu8WPXsiV-AMSRMUEmVOhvmw

###

DELETE http://localhost:3001/tasks/5f7aec35e92042141c08ab9c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InBvZHBpdmFzbmlrMjI4Iiwibmlja05hbWUiOiJwb2RwaXZhc25pazIyOCIsImZpcnN0TmFtZSI6IkFydGVtIiwibGFzdE5hbWUiOiJNaXJvbm92IiwiaWF0IjoxNjAxNTU2MDAzLCJleHAiOjE2MDQxNDgwMDN9.LHTEfBk3A2WdlistOgBZu8WPXsiV-AMSRMUEmVOhvmw

###

PATCH http://localhost:3001/tasks/5f7adc68e92042141c08ab9a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InBvZHBpdmFzbmlrMjI4Iiwibmlja05hbWUiOiJwb2RwaXZhc25pazIyOCIsImZpcnN0TmFtZSI6IkFydGVtIiwibGFzdE5hbWUiOiJNaXJvbm92IiwiaWF0IjoxNjAxNTU2MDAzLCJleHAiOjE2MDQxNDgwMDN9.LHTEfBk3A2WdlistOgBZu8WPXsiV-AMSRMUEmVOhvmw

{
    "description": "Today!!"
}

###

GET http://localhost:3001/auth/5f68b1d468a7638212b65cef